#!/usr/bin/php
<?php
//define('SMTP_PHPMAILER','true');
define('SENDMAIL_PHPMAILER','true');
chdir(__DIR__);

$page = new pcntl('
super javascript;

load_extension adodb refby _ADODB_; 
super database;

use mail.bounce_driver;

public cms.cmsrt;
public mail.smtpmail;
public bmail.maildbqueue;

',1,true);	 

//$ret = _m('maildbqueue.sendmail_daemon use 20+100');
$ret = _m('maildbqueue.sendMyMailDaemon use 100');
echo $ret;
$time = (microtime(true) - $_SERVER["REQUEST_TIME_FLOAT"]) / 60;
echo "<!-- 	$time -->";
?>